using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace HVO.AgentControl.Organization;

/// <summary>
/// The validated, canonical content of one immutable container profile
/// revision: a constrained <c>devcontainer.json</c> subset plus an optional
/// Dockerfile fragment that may only extend the approved worker base image.
/// </summary>
/// <remarks>
/// <para>
/// The subset is deliberately closed. Every accepted key is listed in
/// <see cref="AllowedKeys"/>; every key that would change host placement,
/// mounts, ports, privileges, users or the entrypoint is rejected fail-closed
/// with a key-specific reason (<see cref="ForbiddenKeys"/>), and any other key
/// is rejected as unknown. Runtime arguments, volumes, the network mode, the
/// employee/bridge users and the supervisor entrypoint remain controller-owned
/// and are never derived from profile content.
/// </para>
/// <para>
/// Definitions reference the approved worker base symbolically as
/// <see cref="BaseImageReference"/>. The concrete digest is pinned when a
/// revision is built on a host and frozen again at hire approval; the
/// revision itself stays immutable and hermetically validatable without any
/// deployment configuration.
/// </para>
/// </remarks>
public sealed partial class ContainerProfileDefinition
{
    /// <summary>Symbolic reference to the approved worker base image.</summary>
    public const string BaseImageReference = "agentcontrol-worker-base";

    public const int MaximumDefinitionBytes = 64 * 1024;
    public const int MaximumDockerfileFragmentBytes = 16 * 1024;
    public const int MaximumDockerfileFragmentLines = 200;
    public const int MaximumNameLength = 128;
    public const int MaximumEnvironmentValueLength = 256;
    public const int MaximumCommandLength = 1024;
    public const int MaximumCommandArgumentLength = 256;
    public const int MaximumCommandArguments = 16;
    public const int MaximumSummaryLength = 512;
    public const int MaximumTags = 8;
    public const int MaximumTagLength = 32;
    public const int MaximumJsonDepth = 6;

    /// <summary>Root keys this build accepts. Everything else is rejected.</summary>
    public static readonly IReadOnlyList<string> AllowedKeys =
    [
        "name", "image", "build", "features", "containerEnv", "remoteEnv",
        "postCreateCommand", "postStartCommand", "customizations",
    ];

    /// <summary>Root keys rejected with a specific reason because they would move host authority into profile content.</summary>
    public static readonly IReadOnlyDictionary<string, string> ForbiddenKeys = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["runArgs"] = "host runtime arguments are controller-owned",
        ["mounts"] = "mounts are controller-owned private volumes",
        ["workspaceMount"] = "the workspace mount is controller-owned",
        ["workspaceFolder"] = "the workspace folder is fixed at /workspace",
        ["forwardPorts"] = "workers never publish ports",
        ["appPort"] = "workers never publish ports",
        ["portsAttributes"] = "workers never publish ports",
        ["otherPortsAttributes"] = "workers never publish ports",
        ["privileged"] = "privileged containers are not permitted",
        ["capAdd"] = "capabilities are controller-owned",
        ["securityOpt"] = "security options are controller-owned",
        ["init"] = "PID 1 is the fixed worker supervisor",
        ["initializeCommand"] = "host-side commands are not permitted",
        ["onCreateCommand"] = "only postCreateCommand and postStartCommand are supported",
        ["updateContentCommand"] = "only postCreateCommand and postStartCommand are supported",
        ["postAttachCommand"] = "only postCreateCommand and postStartCommand are supported",
        ["waitFor"] = "lifecycle ordering is controller-owned",
        ["remoteUser"] = "the employee user is fixed",
        ["containerUser"] = "the employee user is fixed",
        ["updateRemoteUserUID"] = "the employee user is fixed",
        ["userEnvProbe"] = "the employee shell environment is fixed",
        ["overrideCommand"] = "the entrypoint is the fixed worker supervisor",
        ["shutdownAction"] = "container lifecycle is controller-owned",
        ["dockerComposeFile"] = "Compose-based profiles are not supported",
        ["service"] = "Compose-based profiles are not supported",
        ["runServices"] = "Compose-based profiles are not supported",
        ["dockerFile"] = "use build.dockerfile with a fragment",
        ["context"] = "the build context is generated by the controller",
        ["hostRequirements"] = "placement is decided at approval, not by the profile",
        ["overrideFeatureInstallOrder"] = "feature order is controller-owned",
        ["capabilities"] = "capabilities are controller-owned",
    };

    /// <summary>Dev Container feature identifiers the controller knows how to render hermetically.</summary>
    public static readonly IReadOnlyList<string> AllowedFeatures =
    [
        "ghcr.io/devcontainers/features/dotnet:2",
        "ghcr.io/devcontainers/features/node:1",
        "ghcr.io/devcontainers/features/python:1",
        "ghcr.io/devcontainers/features/github-cli:1",
    ];

    /// <summary>Environment variable names a profile may set for the employee process.</summary>
    public static readonly IReadOnlyList<string> AllowedEnvironmentKeys =
    [
        "TZ", "LANG", "LC_ALL", "EDITOR", "VISUAL",
        "GIT_AUTHOR_NAME", "GIT_AUTHOR_EMAIL", "GIT_COMMITTER_NAME", "GIT_COMMITTER_EMAIL",
        "DOTNET_CLI_TELEMETRY_OPTOUT", "DOTNET_NOLOGO", "DOTNET_SKIP_FIRST_TIME_EXPERIENCE",
        "NPM_CONFIG_UPDATE_NOTIFIER", "NPM_CONFIG_FUND", "PYTHONDONTWRITEBYTECODE", "PIP_DISABLE_PIP_VERSION_CHECK",
    ];

    /// <summary>Dockerfile instructions permitted in a fragment after the base FROM line.</summary>
    public static readonly IReadOnlyList<string> AllowedDockerfileInstructions =
        ["RUN", "ENV", "ARG", "LABEL", "WORKDIR"];

    private static readonly HashSet<string> AllowedKeySet = new(AllowedKeys, StringComparer.Ordinal);
    private static readonly HashSet<string> AllowedFeatureSet = new(AllowedFeatures, StringComparer.Ordinal);
    private static readonly HashSet<string> AllowedEnvironmentKeySet = new(AllowedEnvironmentKeys, StringComparer.Ordinal);
    private static readonly HashSet<string> AllowedDockerfileInstructionSet = new(AllowedDockerfileInstructions, StringComparer.Ordinal);

    private ContainerProfileDefinition(string canonicalJson, string? dockerfileFragment, string contentHash, string? name, bool usesBuild, IReadOnlyList<string> features)
    {
        CanonicalJson = canonicalJson;
        DockerfileFragment = dockerfileFragment;
        ContentHash = contentHash;
        Name = name;
        UsesBuild = usesBuild;
        Features = features;
    }

    /// <summary>Compact JSON with recursively sorted object keys; the persisted form.</summary>
    public string CanonicalJson { get; }

    /// <summary>Normalized fragment (LF line endings, trailing newline) or null when the profile uses the base image directly.</summary>
    public string? DockerfileFragment { get; }

    /// <summary>`sha256:` digest over the canonical JSON and fragment; identical content always hashes identically.</summary>
    public string ContentHash { get; }

    public string? Name { get; }

    /// <summary>True when the revision extends the base through a Dockerfile fragment.</summary>
    public bool UsesBuild { get; }

    public IReadOnlyList<string> Features { get; }

    /// <summary>
    /// Validates the raw definition and optional fragment. Throws
    /// <see cref="OrganizationValidationException"/> with an actionable, safe
    /// message on the first violation; never accepts partially valid content.
    /// </summary>
    public static ContainerProfileDefinition Parse(string? definitionJson, string? dockerfileFragment)
    {
        if (string.IsNullOrWhiteSpace(definitionJson))
            throw new OrganizationValidationException("A definition is required: a JSON object using the supported devcontainer subset.");
        if (Encoding.UTF8.GetByteCount(definitionJson) > MaximumDefinitionBytes)
            throw new OrganizationValidationException($"The definition must be at most {MaximumDefinitionBytes / 1024} KiB.");

        JsonDocument document;
        try
        {
            document = JsonDocument.Parse(definitionJson, new JsonDocumentOptions { MaxDepth = MaximumJsonDepth, CommentHandling = JsonCommentHandling.Disallow, AllowTrailingCommas = false });
        }
        catch (JsonException exception)
        {
            throw new OrganizationValidationException($"The definition is not strict JSON: {SanitizeJsonError(exception)}");
        }

        using (document)
        {
            var root = document.RootElement;
            if (root.ValueKind != JsonValueKind.Object)
                throw new OrganizationValidationException("The definition must be a JSON object.");
            RejectDuplicateKeys(root, "$");

            var seen = new HashSet<string>(StringComparer.Ordinal);
            foreach (var property in root.EnumerateObject())
            {
                if (ForbiddenKeys.TryGetValue(property.Name, out var reason))
                    throw new OrganizationValidationException($"Key '{property.Name}' is not allowed: {reason}.");
                if (!AllowedKeySet.Contains(property.Name))
                    throw new OrganizationValidationException($"Unknown key '{property.Name}'. Supported keys: {string.Join(", ", AllowedKeys)}.");
                seen.Add(property.Name);
            }

            var hasImage = seen.Contains("image");
            var hasBuild = seen.Contains("build");
            if (hasImage == hasBuild)
                throw new OrganizationValidationException(hasImage
                    ? "Use either 'image' or 'build', not both."
                    : $"Either 'image': \"{BaseImageReference}\" or 'build': {{ \"dockerfile\": \"Dockerfile\" }} is required.");

            string? name = null;
            if (root.TryGetProperty("name", out var nameElement))
                name = RequireBoundedString(nameElement, "name", MaximumNameLength);

            if (hasImage)
            {
                var image = RequireString(root.GetProperty("image"), "image");
                if (!string.Equals(image, BaseImageReference, StringComparison.Ordinal))
                    throw new OrganizationValidationException($"'image' must be exactly \"{BaseImageReference}\"; profiles may only extend the approved worker base.");
                if (!string.IsNullOrWhiteSpace(dockerfileFragment))
                    throw new OrganizationValidationException("A Dockerfile fragment is only accepted with 'build'; remove the fragment or switch to 'build'.");
            }
            else
            {
                ValidateBuild(root.GetProperty("build"));
            }

            var features = new List<string>();
            if (root.TryGetProperty("features", out var featuresElement))
                features = ValidateFeatures(featuresElement);
            if (root.TryGetProperty("containerEnv", out var containerEnv))
                ValidateEnvironment(containerEnv, "containerEnv");
            if (root.TryGetProperty("remoteEnv", out var remoteEnv))
                ValidateEnvironment(remoteEnv, "remoteEnv");
            if (root.TryGetProperty("postCreateCommand", out var postCreate))
                ValidateCommand(postCreate, "postCreateCommand");
            if (root.TryGetProperty("postStartCommand", out var postStart))
                ValidateCommand(postStart, "postStartCommand");
            if (root.TryGetProperty("customizations", out var customizations))
                ValidateCustomizations(customizations);

            var normalizedFragment = hasBuild ? NormalizeAndValidateFragment(dockerfileFragment) : null;
            var canonical = Canonicalize(root);
            var hash = "sha256:" + Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(canonical + "\n" + (normalizedFragment ?? string.Empty)))).ToLowerInvariant();
            return new ContainerProfileDefinition(canonical, normalizedFragment, hash, name, hasBuild, features);
        }
    }

    private static void ValidateBuild(JsonElement build)
    {
        if (build.ValueKind != JsonValueKind.Object)
            throw new OrganizationValidationException("'build' must be an object.");
        RejectDuplicateKeys(build, "build");
        var found = false;
        foreach (var property in build.EnumerateObject())
        {
            if (property.Name is "context" or "args" or "target" or "cacheFrom" or "options")
                throw new OrganizationValidationException($"'build.{property.Name}' is not allowed: the build context, arguments, target and cache are generated by the controller.");
            if (!string.Equals(property.Name, "dockerfile", StringComparison.Ordinal))
                throw new OrganizationValidationException($"Unknown key 'build.{property.Name}'. Only 'build.dockerfile' is supported.");
            var value = RequireString(property.Value, "build.dockerfile");
            if (!string.Equals(value, "Dockerfile", StringComparison.Ordinal))
                throw new OrganizationValidationException("'build.dockerfile' must be exactly \"Dockerfile\"; the fragment is supplied separately.");
            found = true;
        }
        if (!found)
            throw new OrganizationValidationException("'build' requires 'dockerfile': \"Dockerfile\".");
    }

    private static List<string> ValidateFeatures(JsonElement features)
    {
        if (features.ValueKind != JsonValueKind.Object)
            throw new OrganizationValidationException("'features' must be an object keyed by feature id.");
        RejectDuplicateKeys(features, "features");
        var result = new List<string>();
        foreach (var feature in features.EnumerateObject())
        {
            if (!AllowedFeatureSet.Contains(feature.Name))
                throw new OrganizationValidationException($"Feature '{Sanitize(feature.Name)}' is not allowed. Supported features: {string.Join(", ", AllowedFeatures)}.");
            if (feature.Value.ValueKind != JsonValueKind.Object)
                throw new OrganizationValidationException($"Feature '{feature.Name}' options must be an object (use {{}} for defaults).");
            RejectDuplicateKeys(feature.Value, "features." + feature.Name);
            foreach (var option in feature.Value.EnumerateObject())
            {
                if (!string.Equals(option.Name, "version", StringComparison.Ordinal))
                    throw new OrganizationValidationException($"Feature '{feature.Name}' option '{Sanitize(option.Name)}' is not allowed; only 'version' is supported.");
                var version = RequireString(option.Value, $"features['{feature.Name}'].version");
                if (!VersionPattern().IsMatch(version))
                    throw new OrganizationValidationException($"Feature '{feature.Name}' version must match {VersionPattern()} (for example \"10.0\", \"22\", \"lts\" or \"latest\").");
            }
            result.Add(feature.Name);
        }
        return result;
    }

    private static void ValidateEnvironment(JsonElement environment, string key)
    {
        if (environment.ValueKind != JsonValueKind.Object)
            throw new OrganizationValidationException($"'{key}' must be an object of variable names to string values.");
        RejectDuplicateKeys(environment, key);
        foreach (var variable in environment.EnumerateObject())
        {
            if (!AllowedEnvironmentKeySet.Contains(variable.Name))
                throw new OrganizationValidationException($"'{key}.{Sanitize(variable.Name)}' is not an allowed variable. Allowed: {string.Join(", ", AllowedEnvironmentKeys)}.");
            var value = RequireString(variable.Value, $"{key}.{variable.Name}");
            if (value.Length > MaximumEnvironmentValueLength)
                throw new OrganizationValidationException($"'{key}.{variable.Name}' must be at most {MaximumEnvironmentValueLength} characters.");
            if (value.Any(c => char.IsControl(c) || c > 0x7E))
                throw new OrganizationValidationException($"'{key}.{variable.Name}' must be printable ASCII without control characters.");
            if (value.Contains("${", StringComparison.Ordinal) || value.Contains("$(", StringComparison.Ordinal))
                throw new OrganizationValidationException($"'{key}.{variable.Name}' must not contain variable or command substitution.");
        }
    }

    private static void ValidateCommand(JsonElement command, string key)
    {
        switch (command.ValueKind)
        {
            case JsonValueKind.String:
                ValidateCommandText(command.GetString()!, key, MaximumCommandLength, shellForm: true);
                break;
            case JsonValueKind.Array:
                var count = 0;
                foreach (var item in command.EnumerateArray())
                {
                    if (++count > MaximumCommandArguments)
                        throw new OrganizationValidationException($"'{key}' may have at most {MaximumCommandArguments} arguments.");
                    if (item.ValueKind != JsonValueKind.String)
                        throw new OrganizationValidationException($"'{key}' array items must be strings.");
                    ValidateCommandText(item.GetString()!, key, MaximumCommandArgumentLength, shellForm: false);
                }
                if (count == 0)
                    throw new OrganizationValidationException($"'{key}' must not be an empty array.");
                break;
            default:
                throw new OrganizationValidationException($"'{key}' must be a string or an array of strings; object (parallel) form is not supported.");
        }
    }

    private static void ValidateCommandText(string value, string key, int maximumLength, bool shellForm)
    {
        if (value.Trim().Length == 0)
            throw new OrganizationValidationException($"'{key}' must not be empty.");
        if (value.Length > maximumLength)
            throw new OrganizationValidationException($"'{key}' must be at most {maximumLength} characters.");
        if (value.Any(c => c is < ' ' or > '~'))
            throw new OrganizationValidationException($"'{key}' must be printable ASCII on a single line.");
        if (shellForm && ShellMetacharacters().IsMatch(value))
            throw new OrganizationValidationException($"'{key}' string form may not use substitution, redirection, pipes, backgrounding or command separators; use the array form or a single '&&' chain.");
    }

    private static void ValidateCustomizations(JsonElement customizations)
    {
        if (customizations.ValueKind != JsonValueKind.Object)
            throw new OrganizationValidationException("'customizations' must be an object.");
        RejectDuplicateKeys(customizations, "customizations");
        foreach (var vendor in customizations.EnumerateObject())
        {
            if (!string.Equals(vendor.Name, "agentcontrol", StringComparison.Ordinal))
                throw new OrganizationValidationException($"'customizations.{Sanitize(vendor.Name)}' is not supported; only 'customizations.agentcontrol' is read.");
            if (vendor.Value.ValueKind != JsonValueKind.Object)
                throw new OrganizationValidationException("'customizations.agentcontrol' must be an object.");
            RejectDuplicateKeys(vendor.Value, "customizations.agentcontrol");
            foreach (var setting in vendor.Value.EnumerateObject())
            {
                switch (setting.Name)
                {
                    case "summary":
                        RequireBoundedString(setting.Value, "customizations.agentcontrol.summary", MaximumSummaryLength);
                        break;
                    case "tags":
                        if (setting.Value.ValueKind != JsonValueKind.Array)
                            throw new OrganizationValidationException("'customizations.agentcontrol.tags' must be an array of slugs.");
                        var tags = 0;
                        foreach (var tag in setting.Value.EnumerateArray())
                        {
                            if (++tags > MaximumTags)
                                throw new OrganizationValidationException($"'customizations.agentcontrol.tags' may have at most {MaximumTags} entries.");
                            var text = RequireString(tag, "customizations.agentcontrol.tags[]");
                            if (text.Length > MaximumTagLength || !TagPattern().IsMatch(text))
                                throw new OrganizationValidationException($"Tags must be lowercase slugs of at most {MaximumTagLength} characters.");
                        }
                        break;
                    default:
                        throw new OrganizationValidationException($"'customizations.agentcontrol.{Sanitize(setting.Name)}' is not supported; only 'summary' and 'tags' are read.");
                }
            }
        }
    }

    private static string? NormalizeAndValidateFragment(string? fragment)
    {
        if (string.IsNullOrWhiteSpace(fragment))
            throw new OrganizationValidationException($"'build' requires a Dockerfile fragment beginning with 'FROM {BaseImageReference}'.");
        if (Encoding.UTF8.GetByteCount(fragment) > MaximumDockerfileFragmentBytes)
            throw new OrganizationValidationException($"The Dockerfile fragment must be at most {MaximumDockerfileFragmentBytes / 1024} KiB.");
        var normalized = fragment.Replace("\r\n", "\n", StringComparison.Ordinal).Replace('\r', '\n');
        if (normalized.Any(c => c != '\n' && c != '\t' && (char.IsControl(c) || c > 0x7E)))
            throw new OrganizationValidationException("The Dockerfile fragment must be printable ASCII.");
        var lines = normalized.Split('\n');
        if (lines.Length > MaximumDockerfileFragmentLines)
            throw new OrganizationValidationException($"The Dockerfile fragment must be at most {MaximumDockerfileFragmentLines} lines.");

        var sawFrom = false;
        var continuation = false;
        for (var index = 0; index < lines.Length; index++)
        {
            var line = lines[index];
            var trimmed = line.Trim();
            if (trimmed.Length == 0 || trimmed.StartsWith('#'))
            {
                if (trimmed.StartsWith("# syntax", StringComparison.OrdinalIgnoreCase) || trimmed.StartsWith("# escape", StringComparison.OrdinalIgnoreCase))
                    throw new OrganizationValidationException($"Line {index + 1}: parser directives are not allowed in a fragment.");
                continue;
            }

            if (continuation)
            {
                RejectContinuationHazards(trimmed, index + 1);
                continuation = trimmed.EndsWith('\\');
                continue;
            }

            var space = trimmed.IndexOfAny([' ', '\t']);
            var instruction = (space < 0 ? trimmed : trimmed[..space]).ToUpperInvariant();
            var arguments = space < 0 ? string.Empty : trimmed[(space + 1)..].Trim();

            if (!sawFrom)
            {
                if (instruction != "FROM")
                    throw new OrganizationValidationException($"Line {index + 1}: the first instruction must be 'FROM {BaseImageReference}'.");
                if (!string.Equals(arguments, BaseImageReference, StringComparison.Ordinal))
                    throw new OrganizationValidationException($"Line {index + 1}: FROM must be exactly '{BaseImageReference}' without a tag, digest, platform or stage alias.");
                sawFrom = true;
                continue;
            }

            if (instruction == "FROM")
                throw new OrganizationValidationException($"Line {index + 1}: only one FROM is allowed; multi-stage fragments are not supported.");
            if (!AllowedDockerfileInstructionSet.Contains(instruction))
                throw new OrganizationValidationException($"Line {index + 1}: '{Sanitize(instruction)}' is not allowed in a fragment. Allowed: {string.Join(", ", AllowedDockerfileInstructions)}.");
            if (instruction == "RUN")
                RejectContinuationHazards(arguments, index + 1);
            if (instruction == "WORKDIR" && !(arguments is "/workspace" || arguments.StartsWith("/workspace/", StringComparison.Ordinal)))
                throw new OrganizationValidationException($"Line {index + 1}: WORKDIR must stay under /workspace.");
            if (instruction == "ENV" && PathAssignment().IsMatch(arguments) && !arguments.Contains("$PATH", StringComparison.Ordinal) && !arguments.Contains("${PATH}", StringComparison.Ordinal))
                throw new OrganizationValidationException($"Line {index + 1}: replacing PATH is not allowed; append with ENV PATH=\"$PATH:...\".");
            continuation = arguments.EndsWith('\\');
        }

        if (!sawFrom)
            throw new OrganizationValidationException($"The Dockerfile fragment must begin with 'FROM {BaseImageReference}'.");
        if (continuation)
            throw new OrganizationValidationException("The Dockerfile fragment ends inside a line continuation.");

        var result = string.Join('\n', lines.Select(line => line.TrimEnd())).TrimEnd('\n') + "\n";
        return result;
    }

    private static void RejectContinuationHazards(string text, int lineNumber)
    {
        if (RunFlagPattern().IsMatch(text))
            throw new OrganizationValidationException($"Line {lineNumber}: RUN flags (--mount, --network, --security) are not allowed.");
        if (text.Contains("/var/run/docker.sock", StringComparison.Ordinal) || text.Contains("docker.sock", StringComparison.Ordinal))
            throw new OrganizationValidationException($"Line {lineNumber}: the Docker socket is never available to a profile.");
    }

    private static void RejectDuplicateKeys(JsonElement element, string path)
    {
        var keys = new HashSet<string>(StringComparer.Ordinal);
        foreach (var property in element.EnumerateObject())
        {
            if (!keys.Add(property.Name))
                throw new OrganizationValidationException($"Duplicate key '{Sanitize(property.Name)}' in {path}.");
        }
    }

    private static string RequireString(JsonElement element, string key)
    {
        if (element.ValueKind != JsonValueKind.String)
            throw new OrganizationValidationException($"'{key}' must be a string.");
        return element.GetString()!;
    }

    private static string RequireBoundedString(JsonElement element, string key, int maximumLength)
    {
        var value = RequireString(element, key).Trim();
        if (value.Length == 0)
            throw new OrganizationValidationException($"'{key}' must not be empty.");
        if (value.Length > maximumLength)
            throw new OrganizationValidationException($"'{key}' must be at most {maximumLength} characters.");
        if (value.Any(char.IsControl))
            throw new OrganizationValidationException($"'{key}' must not contain control characters.");
        return value;
    }

    private static string Canonicalize(JsonElement root)
    {
        using var stream = new MemoryStream();
        using (var writer = new Utf8JsonWriter(stream, new JsonWriterOptions { Indented = false, SkipValidation = false }))
        {
            WriteCanonical(writer, root);
        }
        return Encoding.UTF8.GetString(stream.ToArray());
    }

    private static void WriteCanonical(Utf8JsonWriter writer, JsonElement element)
    {
        switch (element.ValueKind)
        {
            case JsonValueKind.Object:
                writer.WriteStartObject();
                foreach (var property in element.EnumerateObject().OrderBy(p => p.Name, StringComparer.Ordinal))
                {
                    writer.WritePropertyName(property.Name);
                    WriteCanonical(writer, property.Value);
                }
                writer.WriteEndObject();
                break;
            case JsonValueKind.Array:
                writer.WriteStartArray();
                foreach (var item in element.EnumerateArray()) WriteCanonical(writer, item);
                writer.WriteEndArray();
                break;
            default:
                element.WriteTo(writer);
                break;
        }
    }

    private static string SanitizeJsonError(JsonException exception)
    {
        var message = exception.Message;
        var cut = message.IndexOf(" LineNumber:", StringComparison.Ordinal);
        var core = cut > 0 ? message[..cut] : message;
        return exception.LineNumber is { } line ? $"{core} (line {line + 1})" : core;
    }

    private static string Sanitize(string value)
    {
        var trimmed = value.Length > 64 ? value[..64] + "…" : value;
        return new string(trimmed.Select(c => char.IsControl(c) ? '?' : c).ToArray());
    }

    [GeneratedRegex("^(?:[0-9]+(?:\\.[0-9]+){0,2}|lts|latest|none)$", RegexOptions.CultureInvariant)]
    private static partial Regex VersionPattern();

    [GeneratedRegex("^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$", RegexOptions.CultureInvariant)]
    private static partial Regex TagPattern();

    [GeneratedRegex("`|\\$|<|>|\\||;|(?<!&)&(?!&)", RegexOptions.CultureInvariant)]
    private static partial Regex ShellMetacharacters();

    [GeneratedRegex("(?:^|\\s)--(?:mount|network|security)(?:=|\\s)", RegexOptions.CultureInvariant | RegexOptions.IgnoreCase)]
    private static partial Regex RunFlagPattern();

    [GeneratedRegex("(?:^|\\s)PATH(?:=|\\s)", RegexOptions.CultureInvariant)]
    private static partial Regex PathAssignment();
}
