const { chromium, expect } = require(process.env.HVO_PLAYWRIGHT || '@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const root = path.resolve(__dirname, '../..');
const base = process.env.HVO_BASE_URL || 'http://127.0.0.1:5054';
(async () => {
  const browser = await chromium.launch({headless: true, args: ['--no-sandbox']});
  const context = await browser.newContext({viewport: {width: 1440, height: 1100}});
  const errors = [];
  context.on('page', p => p.on('pageerror', e => errors.push(e.message)));
  const page = await context.newPage();
  await page.goto(base);
  await page.getByLabel('Owner password').fill(fs.readFileSync(path.join(root, '.fixture/secrets/owner-password'), 'utf8').trim());
  await page.getByRole('button', {name: 'Sign in', exact: true}).click();
  await expect(page.getByRole('heading', {name:'Overview',exact:true})).toBeVisible();
  await expect(page.locator('.shell')).toHaveAttribute('data-interactive', 'true');
  const fixture = JSON.parse(fs.readFileSync(path.join(root, '.fixture/runtime-a.json')));
  const suffix = Date.now().toString();
  const runtimeName = 'Browser fixture ' + suffix;
  const directory = '/home/agent/workspaces/browser-' + suffix;
  execFileSync('docker', ['exec', '-u', 'agent', 'hvo-agentcontrol-fixture-a', 'mkdir', '-p', directory]);
  execFileSync('docker', ['exec', '-u', 'agent', 'hvo-agentcontrol-fixture-a', 'git', '-C', directory, 'init', '-q']);
  await expect(page.getByRole('button',{name:'Add runtime',exact:true})).toHaveCount(0);
  await expect(page.getByRole('button',{name:'New worker',exact:true})).toHaveCount(0);
  await page.getByRole('navigation',{name:'Administration'}).getByRole('link',{name:'Runtimes',exact:true}).click();
  await expect(page).toHaveURL(base+'/runtimes');
  await expect(page.getByRole('navigation',{name:'Administration'}).getByRole('link',{name:'Runtimes',exact:true})).toHaveClass(/active/);
  await expect(page.locator('.shell')).toHaveAttribute('data-interactive','true');
  await expect(page.getByRole('region',{name:'Worker conversation'})).toHaveCount(0);
  await page.getByRole('button', {name:'Add runtime', exact:true}).click();
  const profile = page.getByRole('region', {name:'Runtime profile'});
  await profile.getByLabel('Name', {exact:true}).fill(runtimeName);
  await profile.getByLabel('SSH host', {exact:true}).fill(fixture.host);
  await profile.getByLabel('SSH username', {exact:true}).fill('agent');
  await profile.getByLabel('SSH authentication').selectOption('privateKey');
  await profile.getByText('Advanced connection settings', {exact:true}).click();
  await profile.getByLabel('Trusted host key').fill(fixture.fingerprint);
  await profile.getByLabel('Credential file reference').fill('fixture-key');
  await profile.getByLabel('OpenCode password reference').fill('server-password');
  await profile.getByLabel('Allowed remote workspace roots').fill('/home/agent/workspaces');
  await profile.getByLabel('Remote state directory').fill('/home/agent/browser-' + suffix);
  await profile.getByLabel('Absolute OpenCode executable').fill('/usr/local/bin/fixture-opencode');
  await profile.getByLabel('Remote API port').fill(String(41000 + Math.floor(Math.random()*10000)));
  await profile.getByRole('button', {name:'Save runtime', exact:true}).click();
  const card = page.locator('article.runtime-card').filter({has:page.getByRole('heading', {name:runtimeName,exact:true})});
  await card.getByRole('button', {name:'Connect / ensure'}).click();
  await expect(card).toContainText('ModelsAvailable', {timeout:40000});
  await page.getByRole('navigation',{name:'Main navigation'}).getByRole('link',{name:'Workers',exact:true}).click();
  await expect(page).toHaveURL(base+'/workers');
  await expect(page.locator('.shell')).toHaveAttribute('data-interactive','true');
  await expect(page.locator('article.runtime-card')).toHaveCount(0);
  await page.getByRole('button', {name:'New worker', exact:true}).click();
  const worker = page.getByRole('region', {name:'New worker'});
  await worker.getByLabel('Runtime').selectOption({label:runtimeName});
  await worker.getByLabel('Worker name').fill('Browser worker ' + suffix);
  await worker.getByLabel('Project', {exact:true}).fill('Browser smoke');
  await worker.getByLabel('Remote workspace directory').fill(directory);
  await worker.getByRole('button', {name:'Inspect workspace models', exact:true}).click();
  await expect(page.getByText('Workspace-specific models are ready to select.', {exact:true})).toBeVisible({timeout:30000});
  await worker.getByLabel('Provider / model').selectOption('fixture/deterministic');
  await worker.getByLabel('Request initial capability report', {exact:false}).uncheck();
  await worker.getByRole('button', {name:'Create worker', exact:true}).click();
  await expect(page).toHaveURL(/\/\?worker=/,{timeout:30000});
  await expect(page.locator('.shell')).toHaveAttribute('data-interactive','true');
  const conversationUrl=page.url();
  await expect(page.getByRole('region',{name:'Worker conversation'}).getByRole('heading',{name:'Browser worker '+suffix,exact:true})).toBeVisible();
  await page.getByRole('navigation').getByRole('link',{name:'Workers',exact:true}).click();
  await expect(page.locator('.shell')).toHaveAttribute('data-interactive','true');
  const inventoryCard=page.locator('.worker-inventory article').filter({hasText:'Browser worker '+suffix});
  await expect(inventoryCard).toContainText(directory);
  await inventoryCard.getByRole('link',{name:'Open conversation',exact:true}).click();
  await expect(page).toHaveURL(conversationUrl);
  await page.getByRole('navigation',{name:'Administration'}).getByRole('link',{name:'Runtimes',exact:true}).click();
  await page.goBack();
  await expect(page).toHaveURL(conversationUrl);
  await expect(page.locator('.shell')).toHaveAttribute('data-interactive','true');
  const conversation = page.getByRole('region', {name:'Worker conversation'});
  await conversation.getByLabel('Task risk').selectOption('low');
  await conversation.getByLabel('Task or follow-up').fill('Browser task <script>window.hvoUnsafe=true</script> [hold]');
  await conversation.getByRole('button', {name:'Send instruction',exact:true}).click();
  await expect(conversation.locator('.badge').first()).toHaveText('Active', {timeout:20000});
  await conversation.getByLabel('Task or follow-up').fill('Second instruction in same conversation [question]');
  await conversation.getByRole('button', {name:'Queue follow-up',exact:true}).click();
  // Closing the browser page does not stop the backend queue or remote process.
  await page.close();
  const resumed = await context.newPage();
  await resumed.goto(conversationUrl);
  await expect(resumed.locator('.shell')).toHaveAttribute('data-interactive', 'true');
  await expect(resumed.getByRole('region',{name:'Worker conversation'}).getByRole('heading',{name:'Browser worker '+suffix,exact:true})).toBeVisible();
  const detail = resumed.getByRole('region', {name:'Worker conversation'});
  await expect(detail.getByRole('heading', {name:'Question from worker'})).toBeVisible({timeout:30000});
  await detail.getByRole('radio', {name: /One/}).check();
  await detail.getByRole('button', {name:'Send answers', exact:true}).click();
  await expect(detail.locator('.message.assistant')).toHaveCount(2, {timeout:30000});
  await expect(detail.locator('.message.user')).toHaveCount(2);
  if (await resumed.evaluate(() => window.hvoUnsafe)) throw new Error('Untrusted transcript executed as HTML');
  await context.newPage().then(async p => { await p.goto(conversationUrl); await expect(p.getByRole('heading',{name:'Browser worker '+suffix,exact:true})).toBeVisible(); await p.close(); });
  // Two independent conversations exercise query navigation and prevent draft/history crossover.
  const secondName='Second browser worker '+suffix, secondDirectory=directory+'-second';
  execFileSync('docker',['exec','-u','agent','hvo-agentcontrol-fixture-a','mkdir','-p',secondDirectory]);
  execFileSync('docker',['exec','-u','agent','hvo-agentcontrol-fixture-a','git','-C',secondDirectory,'init','-q']);
  await resumed.getByRole('navigation').getByRole('link',{name:'Workers',exact:true}).click();
  await expect(resumed.locator('.shell')).toHaveAttribute('data-interactive','true');
  await resumed.getByRole('button',{name:'New worker',exact:true}).click();
  const secondSetup=resumed.getByRole('region',{name:'New worker'});
  await secondSetup.getByLabel('Runtime').selectOption({label:runtimeName});
  await secondSetup.getByLabel('Worker name').fill(secondName);
  await secondSetup.getByLabel('Remote workspace directory').fill(secondDirectory);
  await secondSetup.getByLabel('Provider / model').selectOption('fixture/deterministic');
  await secondSetup.getByRole('button',{name:'Create worker',exact:true}).click();
  await expect(resumed).toHaveURL(/\/\?worker=/,{timeout:30000});
  await expect(resumed.locator('.shell')).toHaveAttribute('data-interactive','true');
  const secondUrl=resumed.url(), secondId=new URL(secondUrl).searchParams.get('worker');
  const firstId=new URL(conversationUrl).searchParams.get('worker');
  await expect(detail.getByRole('heading',{name:secondName,exact:true})).toBeVisible();
  await expect(detail.locator('.message')).toHaveCount(0);
  await detail.getByLabel('Task or follow-up').fill('Unsent draft for second worker');
  await resumed.getByLabel('Agent conversation').selectOption(firstId);
  await expect(resumed).toHaveURL(conversationUrl);
  await expect(detail.getByRole('heading',{name:'Browser worker '+suffix,exact:true})).toBeVisible();
  await expect(detail.getByLabel('Task or follow-up')).toHaveValue('');
  await expect(detail.locator('.message.user')).toHaveCount(2);
  await expect(resumed.getByRole('navigation').getByRole('link',{name:'Overview',exact:true})).toHaveClass(/active/);
  await resumed.reload();
  await expect(resumed.locator('.shell')).toHaveAttribute('data-interactive','true');
  await expect(resumed.getByLabel('Agent conversation')).toHaveValue(firstId);
  await resumed.getByLabel('Agent conversation').selectOption(secondId);
  await expect(resumed).toHaveURL(secondUrl);
  await resumed.goBack();
  await expect(resumed).toHaveURL(conversationUrl);
  await expect(detail.locator('.message.user')).toHaveCount(2);
  const beforeEdit = await (await context.request.get(base+'/api/v1/workers/'+firstId)).json();
  await detail.getByLabel('Task risk').selectOption('low');
  await detail.getByLabel('Task or follow-up').fill('Lifecycle old model [hold]');
  await detail.getByRole('button',{name:'Send instruction',exact:true}).click();
  await expect(detail.locator('.badge').first()).toHaveText('Active',{timeout:20000});
  await detail.getByRole('link',{name:'Edit worker / model',exact:true}).click();
  const editor = resumed.getByRole('region',{name:'Edit worker'});
  await editor.getByRole('button',{name:'Refresh workspace models'}).click();
  await expect(editor.getByLabel('Default provider / model').locator('option[value="fixture/deterministic-alt"]')).toHaveCount(1,{timeout:20000});
  await editor.getByLabel('Worker name',{exact:true}).fill('Edited worker '+suffix);
  await editor.getByLabel('Role / description').fill('Receives arbitrary prompts and reports results.');
  await editor.getByLabel('Default provider / model').selectOption('fixture/deterministic-alt');
  await editor.getByLabel('Reasoning').selectOption('high');
  await editor.getByRole('button',{name:'Save worker',exact:true}).click();
  await expect(editor).toHaveCount(0);
  let editedCard = resumed.locator('.worker-inventory article').filter({has:resumed.getByRole('heading',{name:'Edited worker '+suffix,exact:true})});
  await editedCard.getByRole('link',{name:'Open conversation',exact:true}).click();
  await detail.getByLabel('Task risk').selectOption('low');
  await detail.getByLabel('Task or follow-up').fill('Lifecycle new model [permission]');
  await detail.getByRole('button',{name:/Send instruction|Queue follow-up/}).click();
  await expect(detail.getByRole('heading',{name:'Permission requested'})).toBeVisible({timeout:30000});
  await expect(detail).toContainText('printf fixture');
  await detail.getByRole('button',{name:'Allow once',exact:true}).click();
  await expect(detail.locator('.message.assistant')).toHaveCount(4,{timeout:30000});
  const afterEdit = await (await context.request.get(base+'/api/v1/workers/'+firstId)).json();
  expect(afterEdit.worker.nativeSessionId).toBe(beforeEdit.worker.nativeSessionId);
  const oldCommand=afterEdit.commands.find(x=>x.kind==='Prompt' && JSON.parse(x.payload).text==='Lifecycle old model [hold]');
  const newCommand=afterEdit.commands.find(x=>x.kind==='Prompt' && JSON.parse(x.payload).text==='Lifecycle new model [permission]');
  expect(JSON.parse(oldCommand.executionPayload).modelId).toBe('deterministic');
  expect(JSON.parse(newCommand.executionPayload).modelId).toBe('deterministic-alt');
  expect(JSON.parse(newCommand.executionPayload).variant).toBe('high');
  await resumed.getByRole('navigation').getByRole('link',{name:'Workers',exact:true}).click();
  editedCard = resumed.locator('.worker-inventory article').filter({has:resumed.getByRole('heading',{name:'Edited worker '+suffix,exact:true})});
  await editedCard.getByText('Details & management',{exact:true}).click();
  await expect(editedCard.getByRole('button',{name:'Archive worker',exact:true})).toBeEnabled();
  await editedCard.getByRole('button',{name:'Archive worker',exact:true}).click();
  await expect(editedCard).toHaveCount(0);
  await resumed.getByLabel('Show archived workers').check();
  await editedCard.getByText('Details & management',{exact:true}).click();
  await editedCard.getByRole('button',{name:'Restore worker',exact:true}).click();
  await editedCard.getByRole('link',{name:'Open conversation',exact:true}).click();
  await expect(detail.locator('.message.assistant')).toHaveCount(4);
  const restored=await (await context.request.get(base+'/api/v1/workers/'+firstId)).json();
  expect(restored.worker.nativeSessionId).toBe(beforeEdit.worker.nativeSessionId);
  await resumed.getByRole('navigation').getByRole('link',{name:'Coordination',exact:true}).click();
  await expect(resumed.getByRole('heading',{name:'Coordination',exact:true})).toBeVisible();
  await resumed.setViewportSize({width:390,height:844});
  if(await resumed.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw new Error('Coordination overflows mobile width');
  await resumed.screenshot({path:path.join(root,'artifacts/browser/coordination-mobile.png'),fullPage:true});
  await resumed.goto(conversationUrl);
  await expect(resumed.locator('.shell')).toHaveAttribute('data-interactive','true');
  await resumed.setViewportSize({width:1440,height:1100});
  fs.mkdirSync(path.join(root, 'artifacts/browser'), {recursive:true});
  await resumed.screenshot({path:path.join(root,'artifacts/browser/dashboard.png'), fullPage:true});
  await resumed.setViewportSize({width:390,height:844});
  if(await resumed.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw new Error('Overview overflows mobile width');
  await resumed.screenshot({path:path.join(root,'artifacts/browser/mobile.png'), fullPage:true});
  await resumed.getByRole('navigation').getByRole('link',{name:'Workers',exact:true}).click();
  await expect(resumed.locator('.shell')).toHaveAttribute('data-interactive','true');
  if(await resumed.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw new Error('Workers overflows mobile width');
  await resumed.screenshot({path:path.join(root,'artifacts/browser/workers-mobile.png'),fullPage:true});
  if (errors.length) throw new Error(errors.join('\n'));
  // Explicitly stop only the disposable server this smoke test created.
  await resumed.getByRole('navigation',{name:'Administration'}).getByRole('link',{name:'Runtimes',exact:true}).click();
  await expect(resumed.locator('.shell')).toHaveAttribute('data-interactive','true');
  if(await resumed.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw new Error('Runtimes overflows mobile width');
  await resumed.screenshot({path:path.join(root,'artifacts/browser/runtimes-mobile.png'),fullPage:true});
  const cleanupCard=resumed.locator('article.runtime-card').filter({has:resumed.getByRole('heading',{name:runtimeName,exact:true})});
  await cleanupCard.getByText('Server lifecycle & diagnostics', {exact:true}).click();
  await cleanupCard.getByRole('button',{name:'Stop owned server and its workers'}).click();
  await expect(cleanupCard).toContainText('Disconnected',{timeout:30000});
  console.log('PASS: worker edit while active, frozen queued models, reasoning choice, question choices, permission reply, archive/restore and native session preservation; separate management pages/menu, two-worker switching/draft isolation, conversation links/back/reload, browser sign-in, runtime bootstrap, model/session creation, task + follow-up, queue, question, page close/reopen, second client, safe transcript, desktop/mobile screenshots and no mobile overflow on all three pages. Fixture output, not model inference.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
