version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    exclude-paths:
      - archive/**
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      nuget:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /tests/Browser
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      browser:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /
    exclude-paths:
      - archive/**
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      containers:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    exclude-paths:
      - archive/**
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns: ["*"]
