// <auto-generated />
using HVO.AgentControl.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HVO.AgentControl.Infrastructure.Migrations
{
    [DbContext(typeof(ControlDb))]
    [Migration("20260908063503_TaskBindings")]
    partial class TaskBindings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("HVO.AgentControl.Core.AssignmentRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.CommandAuthority", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("AcknowledgedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcknowledgementData")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorityGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnrollmentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .IsUnique();

                    b.HasIndex("EnrollmentId");

                    b.ToTable("CommandAuthorities");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.CommandRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("AcceptedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Dismissed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutionPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastProgressAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NativeMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgressText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderPoolId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("QueueOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("State", "QueueOrder");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.CoordinationRun", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContinuousSupervision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoordinatorWorkerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecisionCommandId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeGuidance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastDecisionAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastObservation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSupervisorAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRounds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProgressMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CoordinationRuns");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.EvidenceConsumerCursor", b =>
                {
                    b.Property<string>("ConsumerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HistoryGap")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastConsumedSequence")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConsumerId");

                    b.ToTable("EvidenceConsumerCursors");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.EvidenceCursor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CursorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CursorValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnrollmentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastAcknowledgedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastConsumedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId", "CursorName")
                        .IsUnique();

                    b.ToTable("EvidenceCursors");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.EvidenceReadReceipt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("AcknowledgedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AfterSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConsumerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NextSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PageJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId", "AcknowledgedAt");

                    b.ToTable("EvidenceReadReceipts");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.HostRecord", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Sequence");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Hosts");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.InventoryMutationReceipt", b =>
                {
                    b.Property<string>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RequestId");

                    b.ToTable("InventoryMutations");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.JournalEvent", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence");

                    b.HasIndex("WorkerId", "Sequence");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.ModelUsageRecord", b =>
                {
                    b.Property<string>("RuntimeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeMessageId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CacheReadTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CacheWriteTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CostProvenance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ProviderCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReasoningTokens")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SeenInCommandResult")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SeenInTranscript")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkerId")
                        .HasColumnType("TEXT");

                    b.HasKey("RuntimeId", "NativeSessionId", "NativeMessageId");

                    b.HasIndex("WorkerId", "CreatedAt");

                    b.HasIndex("ProviderId", "ModelId", "CreatedAt");

                    b.ToTable("ModelUsage");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.OperatorStatusUpdate", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AcknowledgedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ActiveSetRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoordinationRunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DueAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("MissedIntervals")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PublishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScheduleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceEventSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("CoordinationRunId", "Sequence");

                    b.HasIndex("ScheduleId", "Kind", "DueAt")
                        .IsUnique();

                    b.ToTable("OperatorStatusUpdates");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.OperatorUpdateSchedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("ActiveSetRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoordinationRunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastDueAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastEmittedEventSequence")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NextDueAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoordinationRunId")
                        .IsUnique();

                    b.ToTable("OperatorUpdateSchedules");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.ParticipantEnrollment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdapterType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AuthorityGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("EnrolledAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdapterType");

                    b.HasIndex("State");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.PendingRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyCommandId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId", "Kind", "NativeId")
                        .IsUnique();

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.ProjectRecord", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseBranch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Sequence");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("RepositoryUrl")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.RuntimeEnvironmentRecord", b =>
                {
                    b.Property<string>("RuntimeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DevcontainerPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("RuntimeId");

                    b.HasIndex("ConfigurationProjectId");

                    b.HasIndex("HostId");

                    b.ToTable("RuntimeEnvironments");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.RuntimeRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedRoots")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ApiPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Authentication")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CredentialReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DesiredConnected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Diagnostic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Executable")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HostKeyAlgorithm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HostKeySha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("InstallIfMissing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstalledExecutable")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Labels")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastEventAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastHealthyAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagedServerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassphraseReference")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PrintLogs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PureMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReconnectAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerPasswordReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StateDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Runtimes");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.TaskBindingRecord", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PlacementVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuntimeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionBindingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerSlotId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.HasIndex("WorkItemId")
                        .IsUnique()
                        .HasFilter("State = 'Active'");

                    b.HasIndex("WorkerSlotId")
                        .IsUnique()
                        .HasFilter("State = 'Active'");

                    b.HasIndex("WorkspaceId")
                        .IsUnique()
                        .HasFilter("State = 'Active'");

                    b.ToTable("TaskBindings");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.TaskSessionBindingRecord", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegacyWorkerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskBindingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkerSlotId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("LegacyWorkerId");

                    b.HasIndex("NativeSessionId")
                        .IsUnique()
                        .HasFilter("NativeSessionId <> ''");

                    b.HasIndex("TaskBindingId")
                        .IsUnique();

                    b.HasIndex("WorkerSlotId");

                    b.ToTable("TaskSessionBindings");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.TaskWorkspaceRecord", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuntimeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerSlotId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.HasIndex("WorkItemId");

                    b.HasIndex("WorkerSlotId");

                    b.HasIndex("RuntimeId", "Directory")
                        .IsUnique()
                        .HasFilter("State = 'Active'");

                    b.ToTable("TaskWorkspaces");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.TranscriptMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("NativeCreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NativeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId", "NativeId")
                        .IsUnique();

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.WorkItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentPhase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerWorkerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Branch");

                    b.HasIndex("IssueNumber");

                    b.HasIndex("OwnerWorkerId");

                    b.HasIndex("Repository", "Branch")
                        .IsUnique()
                        .HasFilter("State NOT IN ('Released', 'Abandoned')");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.WorkItemPhase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Evidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerWorkerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemId", "Name")
                        .IsUnique();

                    b.ToTable("WorkItemPhases");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.WorkerRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityCommandId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityReport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CapabilityReportedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HistoryGap")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastModelAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastStatusInquiryAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastToolAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManagedServerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SettingsRevision")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Stale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuntimeId", "Directory")
                        .IsUnique();

                    b.HasIndex("RuntimeId", "ManagedServerId", "NativeSessionId")
                        .IsUnique();

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.WorkerSlotRecord", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Sequence");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("RuntimeId", "Name")
                        .IsUnique();

                    b.ToTable("WorkerSlots");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.WorkspaceClaim", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkspaceClaims");
                });

            modelBuilder.Entity("HVO.AgentControl.GitHub.GitHubAccess", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionsPermission")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChecksPermission")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitStatusesPermission")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InstallationId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PermissionsVerifiedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrivateKeyReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoriesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RetryAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GitHubAccess");
                });

            modelBuilder.Entity("HVO.AgentControl.Infrastructure.ProviderFailureReceipt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PoolId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RetryAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProviderFailureReceipt");
                });

            modelBuilder.Entity("HVO.AgentControl.Infrastructure.ProviderFallbackReceipt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCommandId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFailureCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFailureReceiptId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePoolId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceTaskOutcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceTerminalState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPoolId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceCommandId")
                        .IsUnique();

                    b.ToTable("ProviderFallbackReceipt");
                });

            modelBuilder.Entity("HVO.AgentControl.Infrastructure.ProviderPool", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastCommandId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RetryAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProviderPool");
                });

            modelBuilder.Entity("HVO.AgentControl.Services.ProviderCredential", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecretReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProviderCredential");
                });

            modelBuilder.Entity("HVO.AgentControl.Services.ProviderKeyDelivery", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("KeyRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProviderKeyDelivery");
                });

            modelBuilder.Entity("HVO.AgentControl.Telemetry.RuntimeTelemetryHistoryRecord", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CpuCoreUsage")
                        .HasColumnType("REAL");

                    b.Property<double?>("CpuQuotaPercent")
                        .HasColumnType("REAL");

                    b.Property<long?>("CpuWindowMs")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MemoryBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MemoryLimitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MemoryPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("QuotaCores")
                        .HasColumnType("REAL");

                    b.Property<string>("RuntimeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence");

                    b.HasIndex("RuntimeId", "ObservedAt", "Sequence");

                    b.ToTable("TelemetryHistory");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.RuntimeEnvironmentRecord", b =>
                {
                    b.HasOne("HVO.AgentControl.Core.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationProjectId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HVO.AgentControl.Core.HostRecord", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HVO.AgentControl.Core.RuntimeRecord", null)
                        .WithOne()
                        .HasForeignKey("HVO.AgentControl.Core.RuntimeEnvironmentRecord", "RuntimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HVO.AgentControl.Core.TaskBindingRecord", b =>
                {
                    b.HasOne("HVO.AgentControl.Core.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HVO.AgentControl.Core.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HVO.AgentControl.Core.WorkerSlotRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkerSlotId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HVO.AgentControl.Core.TaskWorkspaceRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HVO.AgentControl.Core.TaskSessionBindingRecord", b =>
                {
                    b.HasOne("HVO.AgentControl.Core.WorkerRecord", null)
                        .WithMany()
                        .HasForeignKey("LegacyWorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HVO.AgentControl.Core.TaskBindingRecord", null)
                        .WithOne()
                        .HasForeignKey("HVO.AgentControl.Core.TaskSessionBindingRecord", "TaskBindingId")
                        .HasPrincipalKey("HVO.AgentControl.Core.TaskBindingRecord", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HVO.AgentControl.Core.WorkerSlotRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkerSlotId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HVO.AgentControl.Core.TaskWorkspaceRecord", b =>
                {
                    b.HasOne("HVO.AgentControl.Core.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HVO.AgentControl.Core.RuntimeRecord", null)
                        .WithMany()
                        .HasForeignKey("RuntimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HVO.AgentControl.Core.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HVO.AgentControl.Core.WorkerSlotRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkerSlotId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HVO.AgentControl.Core.WorkerSlotRecord", b =>
                {
                    b.HasOne("HVO.AgentControl.Core.RuntimeRecord", null)
                        .WithMany()
                        .HasForeignKey("RuntimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
