// <auto-generated />
using HVO.AgentControl.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HVO.AgentControl.Infrastructure.Migrations
{
    [DbContext(typeof(ControlDb))]
    [Migration("20260906212027_ExplicitHostKeyAlgorithm")]
    partial class ExplicitHostKeyAlgorithm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("HVO.AgentControl.Core.AssignmentRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.CommandRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("QueueOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("State", "QueueOrder");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.JournalEvent", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence");

                    b.HasIndex("WorkerId", "Sequence");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.PendingRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyCommandId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId", "Kind", "NativeId")
                        .IsUnique();

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.RuntimeRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedRoots")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ApiPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Authentication")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CredentialReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DesiredConnected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Diagnostic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Executable")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HostKeyAlgorithm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HostKeySha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("InstallIfMissing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Labels")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastEventAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastHealthyAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManagedServerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassphraseReference")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReconnectAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerPasswordReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StateDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Runtimes");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.TranscriptMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("NativeCreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NativeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId", "NativeId")
                        .IsUnique();

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("HVO.AgentControl.Core.WorkerRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HistoryGap")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastModelAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastStatusInquiryAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastToolAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManagedServerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuntimeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Stale")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RuntimeId", "Directory")
                        .IsUnique();

                    b.HasIndex("RuntimeId", "ManagedServerId", "NativeSessionId")
                        .IsUnique();

                    b.ToTable("Workers");
                });
#pragma warning restore 612, 618
        }
    }
}
